### ISSUE TITLE
тут баг..

### ISSUE THREAD

**Issue by Questern** [Solyaris/AlcoFighter#1]
жесть баг лагает  ужас разработчику желаю исправить проблему пока 1 звезда

**Comment by elmosmokinweed** [comment]
> жесть баг лагает ужас разработчику желаю исправить проблему пока 1 звезда

чел ты добейся сначала у него 4 года стажа, он наверное знает, что делает

**Comment by Questern** [comment]
разработчику приношу извенения (обознался) сразу видно опытный пользователь (4 года стажа) с таким спорить я не клавифицирован.. приложению ставлю 5 звезд
